### ISSUE TITLE
Update to Node.js 16 as Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by f-o-w-l** [ad-m/github-push-action#161] opened 2023-03-04 23:04 UTC
When using the Action, GitHub provides the following warning:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ad-m/github-push-action@v0.6.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by ZPascal** [comment] 2023-03-05 08:34
Duplicate of: https://github.com/ad-m/github-push-action/issues/159

**Closed by ZPascal** 2023-03-05 08:34 UTC
