### ISSUE TITLE
Gives failutre error when no changes

### ISSUE THREAD

**Issue by akashp1712** [ad-m/github-push-action#42] opened 2020-01-04 06:14 UTC
It gives an error and shows action failed when there is nothing to commit

```
nothing to commit, working tree clean
##[error]Process completed with exit code 1.
```

My custom action performed some action and in the end, there were no changes to be pushed.
The subsequent action (ad-m/github-push-action) failed.

It should skip and show the success if there are no changes.

**Comment by kevinvanrijn** [comment] 2020-01-04 10:48
I believe this is related to the example in the README not the actual action itself.

The problem is that `git commit` exits with an error code if it has nothing to do causing the workflow to fail.

Changing the Commit files step to only commit when there are changes fixes this:

```yaml
    - name: Commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Add changes"
```

This is one of the things #35 would correct.

**Comment by ad-m** [comment] 2020-01-04 15:44
Duplicate of #33

**Closed by ad-m** 2020-01-04 15:44 UTC
