### ISSUE TITLE
nao sei como resolver esse erro

### ISSUE THREAD

**Issue by mikaellalencar** [ad-m/github-push-action#125] opened 2022-05-10 13:53 UTC
Run crazy-max/ghaction-github-pages@v2.1.3
✅ Use GITHUB_TOKEN
✨ Initializing local git repo
🏃 Copying /home/runner/work/mikaellalencar/mikaellalencar/dist contents to /tmp/github-pages-ExSlED
🔨 Configuring git committer as GitHub <noreply@github.com>
📐 Updating index of working tree
📦 Committing changes
✅ Allow empty commit
🔨 Configuring git author as github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
commit 5f32989fc0377f4d40f91ca0aa9d62a84ec8f280
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue May [10](https://github.com/mikaellalencar/mikaellalencar/runs/6371148244?check_suite_focus=true#step:4:10) [13](https://github.com/mikaellalencar/mikaellalencar/runs/6371148244?check_suite_focus=true#step:4:13):48:53 [20](https://github.com/mikaellalencar/mikaellalencar/runs/6371148244?check_suite_focus=true#step:4:20)[22](https://github.com/mikaellalencar/mikaellalencar/runs/6371148244?check_suite_focus=true#step:4:22) +0000

    Deploy to GitHub pages

 github-contribution-grid-snake.svg | 1 +
 1 file changed, 1 insertion(+)
🏃 Pushing dist directory to output branch on mikaellalencar/mikaellalencar repo
✅ Force push
Error: remote: Permission to mikaellalencar/mikaellalencar.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/mikaellalencar/mikaellalencar.git/': The requested URL returned error: 403

**Comment by ZPascal** [comment] 2022-05-10 14:06
Hi @mikaellalencar, I suspect that your token does not have the appropriate permissions to push to this repository. Please read my comment in this [issue] (https://github.com/ad-m/github-push-action/issues/111#issuecomment-1117904482) which describes what permissions are needed.

**Comment by ZPascal** [comment] 2022-05-22 09:58
Hi @mikaellalencar, is the issue solved? Can we close it?

**Closed** 2022-07-27 20:27 UTC

**Comment by ZPascal** [comment] 2022-07-27 20:30
Hi @mikaellalencar, I think the issue is solved, and I closed it. Feel free to reopen it, if it still occurs.
