### ISSUE TITLE
Push error - require is not defined in ES module scope

### ISSUE THREAD

**Issue by jiyoonlim123** [ad-m/github-push-action#157] opened 2023-02-22 01:21 UTC
This is my workflow app, but it shows following errors.

```
      - name: Push changes
        if: |
          steps.docker-files-changed.outputs.any_changed == 'true' && steps.helm-files-changed.outputs.any_changed == 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```
<img width="2187" alt="image" src="https://user-images.githubusercontent.com/86942129/220495928-295b834b-aa82-401e-accf-bd8a71b7a90a.png">

**Comment by ZPascal** [comment] 2023-02-22 05:47
Hi @jiyoonlim123, I need a bit more information from your side to further debug the case. Could you please forward the complete action file, especially the `runs-on` part? Is it a GTE instance or public GitHub? Is the repository public available?

**Comment by jiyoonlim123** [comment] 2023-02-22 06:27
I delete some confidential code.
It is the private GitHub and I set the push permission to the GitHub token. 
```
    runs-on: [self-hosted]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: recursive
          token: ${{ secrets.ORG_PAT }}

	- name: Update and image version
        id: update-image-version-tag
        run: |
          python hooks/update_image_tag.py

      - name: Commit changed files
        run: |
          git config user.email <USEREMAIL>
          git config user.name <USERNAME>
          git add .
          git status
          git commit -m "bump version to ${{ steps.update-image-version-tag.outputs.image_name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```

**Comment by ZPascal** [comment] 2023-02-22 06:57
@jiyoonlim123 Which image do you are using for the runner? Is it Ubuntu?

**Comment by jiyoonlim123** [comment] 2023-02-22 08:12
> @jiyoonlim123 Which image do you are using for the runner? Is it Ubuntu?

Yes we use Ubuntu 18.04

**Comment by ZPascal** [comment] 2023-02-22 23:25
@jiyoonlim123 I think the issue is related to the used Node.js version. I can of course prepare a PR to create a package.json, but first I want to reproduce the case. As a workaround, I recommend using the [setup-node](https://github.com/actions/setup-node) action beforehand and use node.js version 18 (I'm personally using and testing with Ubuntu 22.04, node.js → v18). BTW: The community support of Ubuntu 18.04 Bionic will be removed end of April. I've also identified, that the community [updated](https://github.com/actions/runner-images/commit/97e33e1df0707080357f1090675d00f30cac82e2) the node.js version a few days ago inside the runner repository of Ubuntu 18.04 to a new minor version.  That could be the reason why it's now not possible anymore to use the action.

**Comment by jiyoonlim123** [comment] 2023-02-22 23:43
Thanks for your help!! I think your opinion is right since I can see some nodejs version warning in the github action log. As you said, I will update the nodejs version.

**Comment by ZPascal** [comment] 2023-02-23 07:10
That's great. If that solves your problem, please close this issue. Thank you.

**Closed** 2023-02-23 07:23 UTC
